---
title: configure-explorer
description: configure-explorer
privilege: TrustedInstaller
actions:

# - Display the full path in title bar - Enabled
- !registryValue: {path: 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\CabinetState', value: 'FullPath', type: REG_DWORD, data: '1'}

# - Increased context options time threshold
- !registryValue: {path: 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer', value: 'MultipleInvokePromptMinimum', type: REG_DWORD, data: '100'}

# - Disable system beeps
- !registryValue: {path: 'HKEY_CURRENT_USER\Control Panel\Sound', value: 'Beep', type: REG_SZ, data: 'no'}

# - Disable Wallpaper JPEG (.jpg) image Compression.
- !registryValue: {path: 'HKEY_CURRENT_USER\Control Panel\Desktop', value: 'JPEGImportQuality', type: REG_DWORD, data: '100'}

# - Remove Gallery
- !registryValue: {path: 'HKEY_CURRENT_USER\Software\Classes\CLSID\{e88865ea-0e1c-4e20-9aa6-edcd0212c87c}', value: 'System.IsPinnedToNameSpaceTree', type: REG_DWORD, data: '0'}

# - Disable shake to minimize
# - Disable sync provider notifications
# - Show file extensions
- !registryValue: {path: 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'DisallowShaking', type: REG_DWORD, data: '1'}
- !registryValue: {path: 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'ShowSyncProviderNotifications', type: REG_DWORD, data: '0'}
- !registryValue: {path: 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'HideFileExt', type: REG_DWORD, data: '0'}

# - launch File Explorer to this pc
- !registryValue: {path: 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'LaunchTo', type: REG_DWORD, data: '1'}

# - Clear history of recently opened documents on exit
- !registryValue: {path: 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', value: 'ClearRecentDocsOnExit', type: REG_DWORD, data: '1'}

# - Disable show files from office.com
- !registryValue: {path: 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Explorer', value: 'DisableGraphRecentItems', type: REG_DWORD, data: '1'}

# - Remove 3D objects from explorer pane
- !registryValue: {path: 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\{0DB7E03F-FC29-4DC6-9020-FF41B59E513A}', operation: delete}
- !registryValue: {path: 'HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Explorer\MyComputer\NameSpace\{0DB7E03F-FC29-4DC6-9020-FF41B59E513A}', operation: delete}

# - Windows low disk space checking - Disabled
# ------> (Also prevents idle hard disks from going into standby)
- !registryValue: {path: 'HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer', value: 'NoLowDiskSpaceChecks', type: REG_DWORD, data: '1'}

# - Changes the time (milliseconds) it takes for the tooltips to pop up when hovering your mouse over elements to 30 ms. (default = 400 ms)
- !registryValue: {path: 'HKEY_CURRENT_USER\Control Panel\Mouse', value: 'MouseHoverTime', type: REG_SZ, data: '30'}

# - Makes the Start Menu appear almost instantly when you click on the Windows icon in the Taskbar.
- !registryValue: {path: 'HKEY_CURRENT_USER\Control Panel\Desktop', value: 'MenuShowDelay', type: REG_SZ, data: '0'}

# - Specifies time (in milliseconds) that the mouse needs to remain over a window before the window is activated. (current setting is 10 ms)
- !registryValue: {path: 'HKEY_CURRENT_USER\Control Panel\Desktop', value: 'ActiveWndTrkTimeout', type: REG_DWORD, data: '10'}

# - Do not track Shell shortcuts during roaming - Enabled
# ------> https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.WindowsExplorer::LinkResolveIgnoreLinkInfo
- !registryValue: {path: 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', value: 'LinkResolveIgnoreLinkInfo', type: REG_DWORD, data: '1'}

# - Do not use the search-based method when resolving shell shortcuts - Enabled
# ------> https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.StartMenu::NoResolveSearch
- !registryValue: {path: 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', value: 'NoResolveSearch', type: REG_DWORD, data: '1'}

# - Do not use the tracking-based method when resolving shell shortcuts - Enabled
# ------> Disables NTFS tracking features.
# ------> https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.StartMenu::NoResolveTrack
- !registryValue: {path: 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer', value: 'NoResolveTrack', type: REG_DWORD, data: '1'}

# - Disables the blue screen that pops up when you're trying to shutdown or restart, asking you to save your work.
- !registryValue: {path: 'HKEY_CURRENT_USER\Control Panel\Desktop', value: 'AutoEndTasks', type: REG_SZ, data: '0'}

# - HungAppTimeout also specifies how long (5 seconds by default) the system waits for user processes to end after the user clicks/taps on the End task button in Task Manager.
# ------> Changed 2 seconds (2000), default is 5 seconds (5000).
# ------> https://www.tenforums.com/tutorials/97842-change-hungapptimeout-value-windows-10-a.html
- !registryValue: {path: 'HKEY_CURRENT_USER\Control Panel\Desktop', value: 'HungAppTimeout', type: REG_SZ, data: '2000'}

# - The WaitToKillAppTimeout value determines how long the system waits for user processes to end after the user attempts to sign out, restart, or shut down Windows.
# ------> Changed to 2 seconds (2000), default is 20 seconds (20000).
# ------> https://www.eightforums.com/threads/waittokillapptimeout-specify-for-shutdown-in-windows.37424/
- !registryValue: {path: 'HKEY_CURRENT_USER\Control Panel\Desktop', value: 'WaitToKillAppTimeout', type: REG_SZ, data: '2000'}

# - This value controls the timeout period in milliseconds for all low-level hooks.
# ------> https://www.registryrecycler.com/blog/2013/07/speed-up-your-windows-pc-through-registry/
# ------> https://www.quickmacros.com/au/help/api/Au.AHookWin.LowLevelHooksTimeout.html#Au_AHookWin_LowLevelHooksTimeout_remarks
# ------> https://bit.ly/300Dqwh
- !registryValue: {path: 'HKEY_CURRENT_USER\Control Panel\Desktop', value: 'LowLevelHooksTimeout', type: REG_SZ, data: '1000'}
- !registryValue: {path: 'HKU\.DEFAULT\Control Panel\Desktop', value: 'LowLevelHooksTimeout', type: REG_SZ, data: '1000'}

# - Speed up shutdown time by lowering the amount of time it takes the OS to close/kill background Services.
# ------> Changed to 1.5 seconds (1500), default is 5 seconds (5000).
# ------> https://www.sevenforums.com/tutorials/717-shut-down-speed-up.html
- !registryValue: {path: 'HKEY_LOCAL_MACHINE\SYSTEM\ControlSet001\Control', value: 'WaitToKillServiceTimeout', type: REG_SZ, data: '1500'}

# - Turn off display of recent search entries in the File Explorer search box - Enabled
# ------> Additionally this also disables Bing in the Start Menu in Windows 10's May 2020 update (20H1).
# ------> https://www.howtogeek.com/224159/how-to-disable-bing-in-the-windows-10-start-menu/
- !registryValue: {path: 'HKEY_CURRENT_USER\Software\Policies\Microsoft\Windows\Explorer', value: 'DisableSearchBoxSuggestions', type: REG_DWORD, data: '1'}
    
# - Disable the new Weather and News widgets
# ------> Other parts of it can be found in configure-ifeo
- !registryValue: {path: 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Windows Feeds', value: 'EnableFeeds', type: REG_DWORD, data: '0'}
- !registryValue: {path: 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Feeds', value: 'ShellFeedsTaskbarViewMode', type: REG_DWORD, data: '2'}
- !registryValue: {path: 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced', value: 'TaskbarDa', type: REG_DWORD, data: '0'}

# ------> since 22621.1343 builds, Windows 11 tries to reinstall WebExperience even if it is removed and stored in deprovisioned apps list
- !registryValue: {path: 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Dsh', value: 'AllowNewsAndInterests', type: REG_DWORD, data: '0'}

  
# ==========================
# === Attachment Manager ===
# ==========================
- !registryValue: {path: 'HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer', value: 'SmartScreenEnabled', type: REG_SZ, data: 'Off'}

# - Default risk level for file attachments - Disable the warning The Publisher could not be verified
# ------> https://admx.help/?Category=Windows_10_2016&Policy=Microsoft.Policies.AttachmentManager::AM_SetFileRiskLevel
# ------> https://www.tenforums.com/antivirus-firewalls-system-security/17588-disabling-smartscreen-windows-10-does-not-actually-disable.html
- !registryValue: {path: 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Associations', value: 'DefaultFileTypeRisk', type: REG_DWORD, data: '1808'}

# - Do not preserve zone information in file attachments - Enabled
- !registryValue: {path: 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments', value: 'SaveZoneInformation', type: REG_DWORD, data: '1'}

# - Inclusion list for low file types - Enabled (list found below)
# - !registryValue: {path: 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Associations', value: 'LowRiskFileTypes', type: REG_SZ, data: '.avi;.bat;.com;.cmd;.exe;.htm;.html;.lnk;.mpg;.mpeg;.mov;.mp3;.msi;.m3u;.rar;.reg;.txt;.vbs;.wav;.zip;'}
# - Inclusion list for moderate risk file types - Enabled (list found below)
- !registryValue: {path: 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Associations', value: 'ModRiskFileTypes', type: REG_SZ, data: '.bat;.exe;.reg;.vbs;.chm;.msi;.js;.cmd'}

# - Notify antivirus programs when opening attachments - Disabled
# ------> Default is 3
- !registryValue: {path: 'HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments', value: 'ScanWithAntiVirus', type: REG_DWORD, data: '1'}

# - Disables Automatic Folder Type Discovery
# ------> Disabling it fixes the 'folder always loading' issue when a folder contains a lot of media files.  
# ------> https://www.windowslatest.com/2024/03/04/windows-11-can-open-big-folders-in-file-explorer-faster-if-you-turn-off-folder-discovery/
- !registryValue: {path: 'HKEY_CURRENT_USER\SOFTWARE\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell', value: 'FolderType', type: REG_SZ, data: 'NotSpecified'} 

# - Force explorer to use high performance GPU
- !registryValue: { path: 'HKEY_CURRENT_USER\Software\Microsoft\DirectX\UserGpuPreferences', value: 'C:\Windows\explorer.exe', type: REG_SZ, data: 'GpuPreference=2;' }

# - Disable  "Include account-based insights, recent, favorite and recommended" for OneDrive in File Explorer
- !registryValue: { path: 'HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\Explorer', value: 'DisableGraphRecentItems', type: REG_DWORD, data: '1' }

# - Disable the new Spotlight icon on Desktop
- !registryValue: { path: 'HKLM\Software\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel', value: '{2cc5ca98-6485-489a-920e-b3e88a6ccce3}', type: REG_DWORD, data: '1' }